"""FastAPI application factory for ``eq-chatbot serve``.

Endpoints:

* ``GET /health`` (no auth) — liveness probe with version + uptime.
* ``GET /providers`` — static catalog of available provider names.
* ``POST /models`` — per-provider model list; body carries ``api_key`` so it
  doesn't leak into URL strings or access logs.
* ``POST /chat`` — single-shot chat completion → :class:`ChatResponse`.
* ``POST /chat/stream`` — Server-Sent-Events stream of token deltas.

All non-health endpoints are guarded by :class:`~auth.BearerTokenMiddleware`.
The auth token is generated by the parent process and passed in via the CLI
``--auth-token-fd`` flag.
"""

from __future__ import annotations

import json
import time
from typing import Any

from fastapi import FastAPI, HTTPException, status
from sse_starlette.sse import EventSourceResponse

from eq_chatbot_core.providers import (
    AuthenticationError,
    ContextLengthError,
    OverloadedError,
    ProviderError,
    RateLimitError,
    get_provider,
)
from eq_chatbot_core.server.auth import BearerTokenMiddleware
from eq_chatbot_core.server.models import (
    ChatRequest,
    ChatResponse,
    HealthResponse,
    ListModelsRequest,
    ProviderInfo,
)
from eq_chatbot_core.server.streaming import stream_chunk_to_sse_events
from eq_chatbot_core.version import __version__

# Hardcoded provider catalog. Mirrors the dispatch table in
# eq_chatbot_core.providers.__init__.get_provider() — keep in sync when adding
# providers there.
_CLOUD_PROVIDERS: list[str] = [
    "openai",
    "anthropic",
    "langdock",
    "openrouter",
    "mammouth",
    "azure",
    "vertex",
]
_LOCAL_PROVIDERS: list[str] = ["local", "lm_studio", "lmstudio", "ollama"]


def create_app(auth_token: str) -> FastAPI:
    """Build a FastAPI app with auth middleware bound to ``auth_token``."""

    app = FastAPI(
        title="eq-chatbot-server",
        version=__version__,
        description="Local LLM gateway for cross-language eq_chatbot_core integrations",
        docs_url="/docs",
        openapi_url="/openapi.json",
    )

    app.state.start_time = time.monotonic()
    app.add_middleware(BearerTokenMiddleware, expected_token=auth_token)

    @app.get("/health", response_model=HealthResponse, tags=["meta"])
    async def health() -> HealthResponse:
        uptime = time.monotonic() - app.state.start_time
        return HealthResponse(ok=True, version=__version__, uptime_seconds=uptime)

    @app.get("/providers", response_model=ProviderInfo, tags=["meta"])
    async def providers() -> ProviderInfo:
        return ProviderInfo(cloud=list(_CLOUD_PROVIDERS), local=list(_LOCAL_PROVIDERS))

    @app.post("/models", tags=["meta"])
    async def list_models(req: ListModelsRequest) -> dict[str, Any]:
        try:
            provider_inst = get_provider(req.provider, api_key=req.api_key, base_url=req.base_url)
            models = provider_inst.list_models()
            return {"models": [_model_to_dict(m) for m in models]}
        except ProviderError as exc:
            raise _provider_error_to_http(exc) from exc
        except ValueError as exc:
            # Unknown provider name from get_provider()
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.post("/chat", response_model=ChatResponse, tags=["chat"])
    async def chat(req: ChatRequest) -> ChatResponse:
        try:
            provider_extras = req.provider_extra or {}
            provider_inst = get_provider(
                req.provider,
                api_key=req.api_key,
                base_url=req.base_url,
                **provider_extras,
            )
            extras = req.extra or {}
            llm_response = provider_inst.chat_completion(
                messages=[m.model_dump(exclude_none=True) for m in req.messages],
                model=req.model,
                temperature=req.temperature,
                max_tokens=req.max_tokens,
                tools=req.tools,
                **extras,
            )
            return ChatResponse(
                content=llm_response.content,
                model=llm_response.model,
                input_tokens=llm_response.input_tokens,
                output_tokens=llm_response.output_tokens,
                finish_reason=llm_response.finish_reason,
                tool_calls=llm_response.tool_calls or [],
            )
        except ProviderError as exc:
            raise _provider_error_to_http(exc) from exc
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc

    @app.post("/chat/stream", tags=["chat"])
    async def chat_stream(req: ChatRequest) -> EventSourceResponse:
        # Validate provider eagerly so a bad provider name returns a clean 400
        # instead of an SSE stream containing only an error event.
        try:
            provider_extras = req.provider_extra or {}
            provider_inst = get_provider(
                req.provider,
                api_key=req.api_key,
                base_url=req.base_url,
                **provider_extras,
            )
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except ProviderError as exc:
            raise _provider_error_to_http(exc) from exc

        extras = req.extra or {}
        message_dicts = [m.model_dump(exclude_none=True) for m in req.messages]

        def event_iterator():  # type: ignore[no-untyped-def]
            try:
                chunks = provider_inst.stream_completion(
                    messages=message_dicts,
                    model=req.model,
                    temperature=req.temperature,
                    max_tokens=req.max_tokens,
                    tools=req.tools,
                    **extras,
                )
                yield from stream_chunk_to_sse_events(chunks)
            except ProviderError as exc:
                yield {"event": "error", "data": _provider_error_to_json(exc)}
            except Exception as exc:  # noqa: BLE001 — surface unexpected errors to client
                yield {
                    "event": "error",
                    "data": json.dumps({"error": str(exc), "type": type(exc).__name__}),
                }

        return EventSourceResponse(event_iterator())

    return app


def _model_to_dict(model: Any) -> dict[str, Any]:
    """Convert :class:`ModelInfo` (dataclass) or a dict to JSON-serializable form."""
    if hasattr(model, "id"):
        return {
            "id": model.id,
            "name": getattr(model, "name", model.id),
            "provider": getattr(model, "provider", ""),
            "context_length": getattr(model, "context_length", None),
            "supports_streaming": getattr(model, "supports_streaming", True),
            "supports_tools": getattr(model, "supports_tools", True),
            "supports_vision": getattr(model, "supports_vision", False),
        }
    if isinstance(model, dict):
        return model
    return {"id": str(model)}


def _provider_error_to_http(exc: ProviderError) -> HTTPException:
    """Map :class:`ProviderError` subclasses to appropriate HTTP status codes."""
    if isinstance(exc, AuthenticationError):
        code = status.HTTP_401_UNAUTHORIZED
    elif isinstance(exc, RateLimitError):
        code = status.HTTP_429_TOO_MANY_REQUESTS
    elif isinstance(exc, ContextLengthError):
        code = status.HTTP_413_REQUEST_ENTITY_TOO_LARGE
    elif isinstance(exc, OverloadedError):
        code = status.HTTP_503_SERVICE_UNAVAILABLE
    elif exc.status_code:
        code = exc.status_code
    else:
        code = status.HTTP_502_BAD_GATEWAY

    return HTTPException(
        status_code=code,
        detail={
            "error": str(exc),
            "type": type(exc).__name__,
            "provider": exc.provider,
            "retry_after": exc.retry_after,
        },
    )


def _provider_error_to_json(exc: ProviderError) -> str:
    return json.dumps(
        {
            "error": str(exc),
            "type": type(exc).__name__,
            "provider": exc.provider,
            "retry_after": exc.retry_after,
        }
    )
